# Generated by Django 5.2 on 2025-05-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacriacao', models.DateField()),
                ('localizacao', models.CharField(max_length=10000)),
                ('contribuinte', models.IntegerField()),
                ('registro_anterior', models.IntegerField()),
                ('proprietario', models.CharField(max_length=100)),
                ('cpf_proprietario', models.IntegerField()),
                ('ativo', models.BooleanField()),
            ],
        ),
    ]
