# Generated by Django 5.2 on 2025-05-03 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmissaodebens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataTransmissao', models.DateField()),
                ('nomeComprador', models.CharField(max_length=100)),
                ('cpfComprador', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculadetransmissao', to='registro.registro')),
            ],
        ),
    ]
