# Generated by Django 5.2 on 2025-05-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_transmissaodebens'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmissaodebens',
            name='cpfVendedor',
            field=models.CharField(default='1000000', max_length=100),
        ),
        migrations.AddField(
            model_name='transmissaodebens',
            name='nomeVendedor',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
